name: Build Signed APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install Cordova
      - name: Install Cordova
        run: npm install -g cordova

      # Step 4: Create keystore
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
          -keystore $GITHUB_WORKSPACE/learn-dahom.keystore \
          -alias learn-dahom \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=Learn Dahom, OU=Dev, O=LearnDahom, L=City, S=State, C=IN"

      # Step 5: Create Cordova project
      - name: Create Project
        run: |
          cordova create app com.learn.dahom LearnDahom
          cd app
          rm -rf www
          cp -r ../www www
          cordova platform add android

      # Step 6: Debug keystore location
      - name: Verify Keystore Exists
        run: ls -l $GITHUB_WORKSPACE

      # Step 7: Build SIGNED APK
      - name: Build Signed APK
        run: |
          cd app
          cordova build android --release \
          -- \
          --keystore=$GITHUB_WORKSPACE/learn-dahom.keystore \
          --storePassword=123456 \
          --password=123456 \
          --alias=learn-dahom \
          --packageType=bundle,apk

      # Step 8: Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: learn-dahom-signed-apk
          path: /home/runner/work/logic-app/logic-app/platforms/android/app/build/outputs/apk/release/app-release.apk
          
